function f = f(in1,u)
%F
%    F = F(IN1,U)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    17-Oct-2020 14:33:20

x1 = in1(1,:);
x2 = in1(2,:);
f = [x2;-x1-u.*x2.*(x1.^2-1.0)];
